import {
  AddIcon,
  ArrowBackIcon,
  ArrowDownIcon,
  ArrowForwardIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowUpDownIcon,
  AtSignIcon,
  AttachmentIcon,
  BellIcon,
  CalendarIcon,
  ChatIcon,
  CheckIcon,
  CheckCircleIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CloseIcon,
  CopyIcon,
  DeleteIcon,
  DownloadIcon,
  DragHandleIcon,
  EditIcon,
  EmailIcon,
  ExternalLinkIcon,
  HamburgerIcon,
  InfoIcon,
  InfoOutlineIcon,
  LinkIcon,
  LockIcon,
  MinusIcon,
  MoonIcon,
  NotAllowedIcon,
  PhoneIcon,
  PlusSquareIcon,
  QuestionIcon,
  QuestionOutlineIcon,
  RepeatIcon,
  RepeatClockIcon,
  SearchIcon,
  Search2Icon,
  SettingsIcon,
  SmallAddIcon,
  SmallCloseIcon,
  SpinnerIcon,
  StarIcon,
  SunIcon,
  TimeIcon,
  TriangleDownIcon,
  TriangleUpIcon,
  UnlockIcon,
  UpDownIcon,
  ViewIcon,
  ViewOffIcon,
  WarningIcon,
  WarningTwoIcon,
} from "@chakra-ui/icons";

const iconsMap = {
  CI_AddIcon: AddIcon,
  CI_ArrowBackIcon: ArrowBackIcon,
  CI_ArrowDownIcon: ArrowDownIcon,
  CI_ArrowForwardIcon: ArrowForwardIcon,
  CI_ArrowLeftIcon: ArrowLeftIcon,
  CI_ArrowRightIcon: ArrowRightIcon,
  CI_ArrowUpIcon: ArrowUpIcon,
  CI_ArrowUpDownIcon: ArrowUpDownIcon,
  CI_AtSignIcon: AtSignIcon,
  CI_AttachmentIcon: AttachmentIcon,
  CI_BellIcon: BellIcon,
  CI_CalendarIcon: CalendarIcon,
  CI_ChatIcon: ChatIcon,
  CI_CheckIcon: CheckIcon,
  CI_CheckCircleIcon: CheckCircleIcon,
  CI_ChevronDownIcon: ChevronDownIcon,
  CI_ChevronLeftIcon: ChevronLeftIcon,
  CI_ChevronRightIcon: ChevronRightIcon,
  CI_ChevronUpIcon: ChevronUpIcon,
  CI_CloseIcon: CloseIcon,
  CI_CopyIcon: CopyIcon,
  CI_DeleteIcon: DeleteIcon,
  CI_DownloadIcon: DownloadIcon,
  CI_DragHandleIcon: DragHandleIcon,
  CI_EditIcon: EditIcon,
  CI_EmailIcon: EmailIcon,
  CI_ExternalLinkIcon: ExternalLinkIcon,
  CI_HamburgerIcon: HamburgerIcon,
  CI_InfoIcon: InfoIcon,
  CI_InfoOutlineIcon: InfoOutlineIcon,
  CI_LinkIcon: LinkIcon,
  CI_LockIcon: LockIcon,
  CI_MinusIcon: MinusIcon,
  CI_MoonIcon: MoonIcon,
  CI_NotAllowedIcon: NotAllowedIcon,
  CI_PhoneIcon: PhoneIcon,
  CI_PlusSquareIcon: PlusSquareIcon,
  CI_QuestionIcon: QuestionIcon,
  CI_QuestionOutlineIcon: QuestionOutlineIcon,
  CI_RepeatIcon: RepeatIcon,
  CI_RepeatClockIcon: RepeatClockIcon,
  CI_SearchIcon: SearchIcon,
  CI_Search2Icon: Search2Icon,
  CI_SettingsIcon: SettingsIcon,
  CI_SmallAddIcon: SmallAddIcon,
  CI_SmallCloseIcon: SmallCloseIcon,
  CI_SpinnerIcon: SpinnerIcon,
  CI_StarIcon: StarIcon,
  CI_SunIcon: SunIcon,
  CI_TimeIcon: TimeIcon,
  CI_TriangleDownIcon: TriangleDownIcon,
  CI_TriangleUpIcon: TriangleUpIcon,
  CI_UnlockIcon: UnlockIcon,
  CI_UpDownIcon: UpDownIcon,
  CI_ViewIcon: ViewIcon,
  CI_ViewOffIcon: ViewOffIcon,
  CI_WarningIcon: WarningIcon,
  CI_WarningTwoIcon: WarningTwoIcon,
};

export default iconsMap;
